### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by demokritos** [xylosper/bomi#359]
Arch Linux bomi-git 0.9.10.r10
나오는 에러 메시지가 없습니다.
```
$ bomi --debug --log-level trace
세그멘테이션 오류 (core dumped)
```
gdb
```
(gdb) run
Starting program: /usr/bin/bomi 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd2c44700 (LWP 30641)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff11ccbac in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff11ccbac in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#1  0x00007ffff19f2732 in QGuiApplication::screenAdded(QScreen*) ()
   from /usr/lib/libQt5Gui.so.5
#2  0x00007ffff19e92e0 in QPlatformIntegration::screenAdded(QPlatformScreen*)
    () from /usr/lib/libQt5Gui.so.5
#3  0x00007fffd411773f in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#4  0x00007fffd4117f6b in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#5  0x00007fffd411b8a4 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#6  0x00007fffd41304ab in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#7  0x00007ffff19ea012 in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) () from /usr/lib/libQt5Gui.so.5
#8  0x00007ffff19f5bcb in QGuiApplicationPrivate::createPlatformIntegration()
    () from /usr/lib/libQt5Gui.so.5
#9  0x00007ffff19f6a1d in QGuiApplicationPrivate::createEventDispatcher() ()
   from /usr/lib/libQt5Gui.so.5
#10 0x00007ffff11a0f1f in QCoreApplication::init() ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007ffff11a0f86 in QCoreApplication::QCoreApplication(QCoreApplicationPrivate&) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff19f8d99 in QGuiApplication::QGuiApplication(QGuiApplicationPrivate&) () from /usr/lib/libQt5Gui.so.5
#13 0x00007ffff1fb720d in QApplication::QApplication(int&, char**, int) ()
   from /usr/lib/libQt5Widgets.so.5
#14 0x0000000000585230 in App::App(int&, char**) ()
#15 0x0000000000455f55 in main ()
```
전에 빌드했던 bomi-git 0.9.5.r20은 잘 되는데 테스트 해 본 v0.9.9, v0.9.10, 0.9.10.r10은 
Segfault가 납니다.

**Comment by ahjolinna** [comment]
I have this same problem with arch-testing and bomi-git......btw. I just broke my arch/plasma5 installation on my ultrabook so I cant test anything for a while

**Comment by xylosper** [comment]
혹시 testing 저장소 쓰고 계신가요?

**Comment by demokritos** [comment]
네, testing 저장소를 쓰고 있습니다. 그래서 그런 건가요?
testing 저장소에서는 gcc, gcc-libs, binutils, glibc 등이 설치되어 있네요.

**Comment by xylosper** [comment]
그래서그런건지는 모르겠지만 비슷한보고가있었고 testing패키지들을 지우니까 해결됬다는 보고는 있습니다.

**Comment by demokritos** [comment]
GCC 5에서 C++ ABI를 변경하였다네요. Testing 저장소에 있는 GCC가 5.1.0이고 아직 qt5나 libstdc++는 extra 저장소에 있어서 ABI 호환이 되지 않나 봅니다. C++ 패키지들이 모두 GCC 5로 빌드되어 올라오길 기다려야 할 것 같습니다.
